config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'
  resources :sessions, only: %i[new create]
  get 'rooms/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @users = User.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    talked_to_user = User.find_by(name: params[:name]) || User.find_by(id: cookies[:talked_to_user_id])
    cookies[:talked_to_user_id] = talked_to_user.id
    login_user_id = cookies[:login_user_id].to_i
    talked_to_user_id = talked_to_user.id.to_i
    if login_user_id > talked_to_user_id
      first_user_id = talked_to_user_id
      last_user_id = login_user_id
    else
      first_user_id = login_user_id
      last_user_id = talked_to_user_id
    end
    @login_user = User.find_by(id: cookies[:login_user_id])
    @talked_user = User.find_by(id: cookies[:talked_to_user_id])
    @messages = Message.where(first_user_id: first_user_id, last_user_id: last_user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])
    if user
      cookies[:login_user_id] = user.id
      redirect_to homes_show_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/homes/show.html.erb
<h1>トップページ</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.name, rooms_show_url(name: user.name) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionCablePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message">
  <p><%= message.content %></p>
</div>

app/views/rooms/show.html.erb
<h1>Chat room</h1>

<h2><%= "あなた:#{@login_user.name}" %></h2>
<h2><%= "あいて:#{@talked_user.name}" %></h2>

<div id="messages">
  <%= render @messages %>
</div>

<form>
  <label>Say something:</label><br>
  <input type="text" data-behavior="room_speaker">
</form>